# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum a numeric vector using loop unrolling
#'
#' @param x A numeric vector
#' @return The sum of all elements
#' @export
sum_array_cpp <- function(x) {
    .Call(`_templateRpackage_sum_array_cpp`, x)
}

